repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Latest stable version of black
    hooks:
      - id: black

#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.10.1  # Stable version for isort
#    hooks:
#      - id: isort
