name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:\$PATH" >> $GITHUB_ENV

      - name: Install dependencies for Data Handler
        working-directory: ./apps/data_handler
        env:
          PATH: ${{ env.PATH }}:$HOME/.local/bin
        run: |
          poetry install

      - name: Run Tests for Data Handler
        working-directory: ./apps/data_handler
        env:
          PATH: ${{ env.PATH }}:$HOME/.local/bin
        run: |
          pytest apps/data_handler

      - name: Install dependencies for Shared
        working-directory: ./apps/shared
        env:
          PATH: ${{ env.PATH }}:$HOME/.local/bin
        run: |
          poetry install

      - name: Run Tests for Shared
        working-directory: ./apps/shared
        env:
          PATH: ${{ env.PATH }}:$HOME/.local/bin
        run: |
          pytest apps/shared
