name: Pylint Checc


on:
  push:
    paths:
      - 'apps/data_handler/**/*.py'
  pull_request:
    paths:
      - 'apps/data_handler/**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          python -m pylint --rcfile=.pylintrc ./apps/data_handler/**/*.py
